### ISSUE TITLE
No reference of gigachad in readme

### ISSUE THREAD

**Issue by Dank-del** [GigaUserbot/GIGA#1]
add gigachad pic for extra based

**Comment by Dank-del** [comment]
![telegram-cloud-photo-size-4-5953189371270245992-y](https://user-images.githubusercontent.com/63096193/182034161-e76278dd-0282-45ef-a396-cb8be0a157cf.jpg)

**Comment by celestix** [comment]
bruh lmao

**Comment by Divkix** [comment]
@Dank-del We will surely add this 👍

**Comment by celestix** [comment]
> 

lmfao
