### ISSUE TITLE
Pre-Build Binaries 

### ISSUE THREAD

**Issue by celestix** [GigaUserbot/GIGA#15]
**GIGA** needs a store of pre-built binaries to be used for updating the *userbot*. since **Go is a compiled language**, we cannot be certain about the platform which would be providing go executable in the runtime container. Hence the use of pre-built binaries become a necessary step to be taken for the interest of public which would use unlisted platforms for hosting the *userbot*.

Here is some important information about the idea:
**Go Version**: `1.18`
**Target Container**: `Docker`
**Binaries Storage**: `Github Actions` `(YET TO BE DECIDED)`
**Architectures**: `x86` `x64` 
**GOOS**: `darwin`, `unix`, `linux`, `windows` 

**Proposal By**: [Veer (Anony)](https://github.com/anonyindian)
**Assigned To**: [Divkix](https://github.com/divkix)

**SUGGESTIONS ARE WELCOME**

**©2022 Project GIGA**

**Comment by Divkix** [comment]
This has been implemented using goreleaser
